// <auto-generated />
using System;
using ActiveAssets.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActiveAssets.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActiveAssets.DAL.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Cedula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Cedula");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ActiveAssets.DAL.Entities.Inmueble", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantBathrooms")
                        .HasColumnType("int");

                    b.Property<int>("CantHabitaciones")
                        .HasColumnType("int");

                    b.Property<Guid>("CedulaPropietario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTipoInmueble")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Metros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrecioAlquiler")
                        .HasColumnType("float");

                    b.Property<double>("PrecioVenta")
                        .HasColumnType("float");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Inmuebles");
                });

            modelBuilder.Entity("ActiveAssets.DAL.Entities.Propietario", b =>
                {
                    b.Property<Guid>("Cedula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Cedula");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Propietarios");
                });

            modelBuilder.Entity("ActiveAssets.DAL.Entities.SolicitudCompraArriendo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CedulaCliente")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdInmueble")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("SolicitudesCompraArriendo");
                });

            modelBuilder.Entity("ActiveAssets.DAL.Entities.TelefonoCliente", b =>
                {
                    b.Property<Guid>("CedulaCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("CedulaCliente");

                    b.HasIndex("CedulaCliente")
                        .IsUnique();

                    b.ToTable("TelefonosClientes");
                });

            modelBuilder.Entity("ActiveAssets.DAL.Entities.TelefonoPropietario", b =>
                {
                    b.Property<Guid>("CedulaPropietario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("CedulaPropietario");

                    b.HasIndex("CedulaPropietario")
                        .IsUnique();

                    b.ToTable("TelefonosPropietarios");
                });

            modelBuilder.Entity("ActiveAssets.DAL.Entities.TipoInmueble", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("TiposInmuebles");
                });
#pragma warning restore 612, 618
        }
    }
}
